"""Pydantic schemas for the PQC Messenger API."""

from __future__ import annotations

from typing import Optional

from pydantic import BaseModel, EmailStr, Field

__all__ = [
    "RegisterRequest",
    "RegisterResponse",
    "LoginRequest",
    "LoginResponse",
    "UserProfile",
    "KeyGenerateRequest",
    "KeyGenerateResponse",
    "MessageSendRequest",
    "MessageSendResponse",
]


class RegisterRequest(BaseModel):
    email: EmailStr
    password: str = Field(min_length=8, max_length=256)
    display_name: str = Field(min_length=1, max_length=80)
    generate_on_device: bool = False


class RegisterResponse(BaseModel):
    user_id: str
    key_id: Optional[str] = None
    public_key: Optional[str] = None
    auth_token: str


class UserProfile(BaseModel):
    user_id: str
    email: EmailStr
    display_name: str


class LoginRequest(BaseModel):
    email: EmailStr
    password: str = Field(min_length=8, max_length=256)


class LoginResponse(BaseModel):
    auth_token: str
    user_profile: UserProfile


class KeyGenerateRequest(BaseModel):
    auth_token: str
    generate_on_device: bool = False


class KeyGenerateResponse(BaseModel):
    key_id: str
    public_key: Optional[str] = None


class MessageSendRequest(BaseModel):
    auth_token: str
    recipient_id: str
    message_body: str = Field(min_length=1, max_length=4096)
    signature: str = Field(
        min_length=1,
        description="Base64-encoded Dilithium signature generated by the sender.",
    )
    public_key_id: str


class MessageSendResponse(BaseModel):
    message_id: str
    signature_valid: bool
